# Change these first
owner: hallobayi # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
sites:
  - name: Website
    url: https://halobayi.co.id/
    expectedStatusCodes:
      - 200
      - 301
      - 302
      - 500
      - 503
  - name: Mail Server
    url: https://mail.halobayi.co.id/
    expectedStatusCodes:
      - 200
      - 301
      - 302
  - name: SIM Hai
    url: https://sim.halobayi.co.id/
    expectedStatusCodes:
      - 200
      - 301
      - 302
assignees: # Users to assign downtime issues (optional)
  - mdestafadilah
status-website:
  links:
    - rel: stylesheet
      href: https://rawcdn.githack.com/hallobayi/status/ca628d5d15015bc7505de40dd349df0ea877f7ca/assets/costume-theme.css
  theme: "light"
  name: Status Web Halo Bayi Indonesia
  cname: status.halobayi.co.id
  logoUrl: https://rawcdn.githack.com/hallobayi/assets/15c41d562d1dd5609e33b2caa5071913abf7d28c/logo_only_hb.png
  introTitle: "**HaloBayi Indonesia** adalah acuan data yang digunakan oleh [Halo Bayi Indonesia](https://www.halobayi.co.id/)."
  introMessage: Halaman ini berfungsi untuk memonitor website yang berhubungan dengan [Halo Bayi Indonesia](https://halobayi.co.id/)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  url: "https://status.halobayi.co.id"
  activeIncidents: Insiden Aktif
  allSystemsOperational: Semua sistem beroperasi
  incidentReport: "Laporan insiden #$NUMBER →"
  activeIncidentSummary: Dibuka pada $DATE dengan $POSTS postingan
  incidentTitle: Detail Insiden $NUMBER
  incidentDetails: Detail Insiden
  incidentFixed: Diperbaiki
  incidentOngoing: Sedang berlangsung
  incidentOpenedAt: Dibuka pada
  incidentClosedAt: Ditutup pada
  incidentSubscribe: Berlangganan Pembaruan
  incidentViewOnGitHub: Lihat di GitHub
  incidentCommentSummary: Diposting pada $DATE oleh $AUTHOR
  incidentBack: ← Kembali ke semua insiden
  pastIncidents: Insiden Masa Lalu
  pastIncidentsResolved: Diselesaikan dalam $MINUTES menit dengan $POSTS postingan
  liveStatus: Status Langsung
  overallUptime: Uptime keseluruhan $UPTIME%
  overallUptimeTitle: Uptime keseluruhan
  averageResponseTime: Waktu respons rata-rata $TIMEms
  averageResponseTimeTitle: Respon rata-rata
  sevelDayResponseTime: Waktu respons 7 hari
  responseTimeMs: Waktu respons (ms)
  up: Aktif
  down: Non-aktif
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: Halaman ini [open source]($REPO), dikembangkan oleh [Muchamad Desta Fadilah](https://github.com/mdestafadilah) dengan menggunakan [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Batas tarif terlampaui
  rateLimitExceededIntro: Anda telah melebihi jumlah permintaan yang dapat Anda lakukan dalam satu jam, jadi Anda harus menunggu sebelum mengakses situs web ini lagi. Sebagai alternatif, Anda dapat menambahkan Token Akses Pribadi GitHub untuk terus menggunakan situs web ini.
  rateLimitExceededWhatDoesErrorMean: Apa arti kesalahan ini?
  rateLimitExceededErrorMeaning: Situs web ini menggunakan API GitHub untuk mengakses data waktu nyata tentang status situs web kami. Secara default, GitHub mengizinkan setiap alamat IP 60 permintaan per jam, yang telah Anda gunakan.
  rateLimitExceededErrorHowCanFix: Bagaimana cara memperbaikinya?
  rateLimitExceededErrorFix: Anda dapat menunggu satu jam lagi dan batas alamat IP Anda akan dipulihkan. Sebagai alternatif, Anda dapat menambahkan Token Akses Pribadi GitHub Anda, yang memberi Anda 5.000 permintaan tambahan per jam.
  rateLimitExceededGeneratePAT: Pelajari cara membuat Token Akses Pribadi
  rateLimitExceededHasSet: Anda memiliki set token akses pribadi.
  rateLimitExceededRemoveToken: Hapus token
  rateLimitExceededGitHubPAT: Token Akses Pribadi GitHub
  rateLimitExceededCopyPastePAT: Salin dan tempel token Anda
  rateLimitExceededSaveToken: Simpan token
  errorTitle: Terjadi kesalahan
  errorIntro: Terjadi kesalahan saat mencoba mendapatkan detail status terbaru.
  errorText: Anda dapat mencoba lagi dalam beberapa saat.
  errorHome: Buka beranda

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
